version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/auth-boiler-plate?schema=public
      - JWT_SECRET=change-this-secret-in-production
      - JWT_EXPIRES_IN="1d"
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - FRONTEND_URL=http://localhost:8080
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_started
    command: >
      sh -c "npm ci &&
             npm run prisma:generate &&
             npm run dev"

  postgres:
    image: postgres:15.5-alpine
    platform: linux/arm64
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth-boiler-plate
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: jcalonso/mailhog:v1.0.1
    platform: linux/arm64
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web interface

volumes:
  postgres_data:
